"""Built-in keyword / topic pool for ThriftyNest.

Each topic is a dict:
    kw      - the target search phrase (long-tail, low competition)
    title   - article title template (may contain {year})
    cat     - category slug (see build_site.py CATEGORY_NAMES)
    type    - comparison | howto | list

The generator picks topics that have not been written yet and never repeats
them. Add your own topics to this list anytime — the pipeline picks them up
on the next run.
"""

TOPICS = [
    # --- kitchen ---
    {"kw": "best air fryer under $50", "cat": "kitchen", "type": "comparison",
     "title": "The 7 Best Air Fryers Under $50 in {year} (Tested & Compared)"},
    {"kw": "best air fryer for one person", "cat": "kitchen", "type": "comparison",
     "title": "Best Air Fryers for One Person in {year}: Small, Cheap & Quiet"},
    {"kw": "best coffee maker under $100", "cat": "kitchen", "type": "comparison",
     "title": "The 5 Best Coffee Makers Under $100 in {year} (Honest Review)"},
    {"kw": "cheap electric kettle that lasts", "cat": "kitchen", "type": "comparison",
     "title": "5 Cheap Electric Kettles That Actually Last (Under $30)"},
    {"kw": "best meal prep containers that don't leak", "cat": "kitchen", "type": "comparison",
     "title": "Best Meal Prep Containers That Don't Leak or Break (Budget Picks)"},
    {"kw": "best slow cooker under $40", "cat": "kitchen", "type": "comparison",
     "title": "Best Slow Cookers Under $40 in {year}: Set It and Forget It, Cheaply"},
    {"kw": "best rice cooker under $50", "cat": "kitchen", "type": "comparison",
     "title": "Best Rice Cookers Under $50: Foolproof Rice Without the Price Tag"},
    {"kw": "best toaster under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Toasters Under $30 That Actually Toast Evenly"},
    {"kw": "best budget blender for smoothies", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Blenders for Smoothies in {year} (Under $50)"},
    {"kw": "how to stock a budget pantry", "cat": "kitchen", "type": "howto",
     "title": "How to Stock a Budget Pantry: 50 Items for Under $100"},
    {"kw": "cheapest way to cook healthy meals", "cat": "kitchen", "type": "howto",
     "title": "The Cheapest Way to Cook Healthy Meals at Home (Real Numbers)"},
    {"kw": "best budget cookware set", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Cookware Sets in {year}: What's Worth Buying"},
    {"kw": "best air fryer toaster oven combo under $100", "cat": "kitchen", "type": "comparison",
     "title": "Best Air Fryer Toaster Oven Combos Under $100 (Two Appliances, One Price)"},
    {"kw": "best budget air fryer for a family of 4", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Air Fryers for a Family of 4 (Big Baskets, Small Prices)"},
    {"kw": "best cheap french press", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap French Presses: Great Coffee for Under $25"},
    {"kw": "best budget pour over coffee maker", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Pour Over Coffee Makers (Under $40)"},
    {"kw": "best budget electric griddle", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Electric Griddles: Pancake Sundays Without the Price"},
    {"kw": "best waffle maker under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Waffle Makers Under $30 (Crispy, Cheap & Easy to Clean)"},
    {"kw": "best cheap stand mixer alternatives", "cat": "kitchen", "type": "howto",
     "title": "Best Cheap Stand Mixer Alternatives: What to Buy Instead"},
    {"kw": "best hand mixer under $25", "cat": "kitchen", "type": "comparison",
     "title": "Best Hand Mixers Under $25 That Actually Last"},
    {"kw": "best immersion blender under $40", "cat": "kitchen", "type": "comparison",
     "title": "Best Immersion Blenders Under $40 (Soup Season, Solved)"},
    {"kw": "best food processor under $60", "cat": "kitchen", "type": "comparison",
     "title": "Best Food Processors Under $60: Prep Work Without the Price Tag"},
    {"kw": "best budget knives set", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Knife Sets: You Don't Need to Spend $200"},
    {"kw": "best chef knife under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Chef Knives Under $30 (The Only Knife Most Cooks Need)"},
    {"kw": "best cheap cutting boards", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Cutting Boards: Wood vs Plastic vs Bamboo"},
    {"kw": "best nonstick pan under $25", "cat": "kitchen", "type": "comparison",
     "title": "Best Nonstick Pans Under $25 (That Don't Peel in a Month)"},
    {"kw": "best budget cast iron skillet", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Cast Iron Skillets: The $20 Pan That Lasts Decades"},
    {"kw": "best budget dutch oven", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Dutch Ovens: Le Creuset Looks for Less"},
    {"kw": "best instant pot alternative under $60", "cat": "kitchen", "type": "comparison",
     "title": "Best Instant Pot Alternatives Under $60 (Multicookers That Deliver)"},
    {"kw": "best budget pressure cooker", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Pressure Cookers: Fast Dinners for Less"},
    {"kw": "electric kettle vs stovetop which is cheaper", "cat": "kitchen", "type": "howto",
     "title": "Electric Kettle vs Stovetop: Which Is Actually Cheaper?"},
    {"kw": "how to meal prep on a budget for beginners", "cat": "kitchen", "type": "howto",
     "title": "How to Meal Prep on a Budget: A Beginner's 7-Day Plan"},
    {"kw": "cheap healthy snacks to meal prep", "cat": "kitchen", "type": "list",
     "title": "15 Cheap Healthy Snacks You Can Meal Prep This Weekend"},
    {"kw": "how to save money on groceries every month", "cat": "kitchen", "type": "howto",
     "title": "How to Save Money on Groceries Every Month (14 Tricks That Add Up)"},
    {"kw": "cheapest meals for a family of four", "cat": "kitchen", "type": "list",
     "title": "The 10 Cheapest Meals for a Family of Four (Under $10 Each)"},
    {"kw": "how to reduce food waste at home", "cat": "kitchen", "type": "howto",
     "title": "How to Reduce Food Waste at Home (and Save $100 a Month)"},
    {"kw": "best budget water filter pitcher", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Water Filter Pitchers: Which Filter Actually Filters?"},
    {"kw": "best cheap lunch ideas for work", "cat": "kitchen", "type": "list",
     "title": "12 Cheap Lunch Ideas for Work (No Microwave Required)"},
    {"kw": "best budget toaster oven", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Toaster Ovens: The Mini Oven That Earns Its Spot"},
    {"kw": "how to cook rice perfectly without a rice cooker", "cat": "kitchen", "type": "howto",
     "title": "How to Cook Rice Perfectly Without a Rice Cooker (Stovetop Method)"},
    {"kw": "best budget juicer", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Juicers: Fresh Juice Without the $300 Machine"},
    # --- organization ---
    {"kw": "how to organize a small kitchen on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize a Small Kitchen on a Budget (12 Cheap Tricks)"},
    {"kw": "best cheap storage bins for closets", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Storage Bins for Closets That Actually Look Good"},
    {"kw": "how to declutter your home in a weekend", "cat": "organization", "type": "howto",
     "title": "How to Declutter Your Home in One Weekend (Room-by-Room Plan)"},
    {"kw": "best drawer organizers under $20", "cat": "organization", "type": "comparison",
     "title": "Best Drawer Organizers Under $20 (Kitchen, Desk & Bathroom)"},
    {"kw": "small apartment storage ideas on a budget", "cat": "organization", "type": "howto",
     "title": "Small Apartment Storage Ideas That Cost Almost Nothing"},
    {"kw": "best under-bed storage containers", "cat": "organization", "type": "comparison",
     "title": "Best Under-Bed Storage Containers: Cheap, Durable & Dust-Free"},
    {"kw": "how to organize a tiny bathroom cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Tiny Bathroom Without Spending Much"},
    {"kw": "best closet organizers under $50", "cat": "organization", "type": "comparison",
     "title": "Best Closet Organizers Under $50 (Shelves, Rods & Bins)"},
    {"kw": "garage organization on a budget", "cat": "organization", "type": "howto",
     "title": "Garage Organization on a Budget: Cheap Ideas That Work"},
    {"kw": "best shoe racks for small spaces", "cat": "organization", "type": "comparison",
     "title": "Best Shoe Racks for Small Spaces (Under $30)"},
    {"kw": "how to organize a closet with little space", "cat": "organization", "type": "howto",
     "title": "How to Organize a Closet with Little Space (The 60/40 Rule)"},
    {"kw": "best cheap closet shelf kits", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Closet Shelf Kits: Double Your Hanging Space"},
    {"kw": "how to organize a pantry cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Pantry Cheaply (No Custom Shelving Needed)"},
    {"kw": "best cheap pantry organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Pantry Organizers: Bins, Risers & Labels Under $25"},
    {"kw": "how to organize kids toys on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize Kids' Toys on a Budget (That Kids Can Maintain)"},
    {"kw": "best cheap toy storage ideas", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Toy Storage Ideas for Small Homes"},
    {"kw": "how to organize a laundry room cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Laundry Room Cheaply in an Afternoon"},
    {"kw": "how to organize paper clutter at home", "cat": "organization", "type": "howto",
     "title": "How to Organize Paper Clutter at Home (The 3-Box System)"},
    {"kw": "best cheap file organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap File Organizers for Home Offices"},
    {"kw": "how to organize cables and cords", "cat": "organization", "type": "howto",
     "title": "How to Organize Cables and Cords (The $10 Solution)"},
    {"kw": "best cheap cable organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Cable Organizers: Clips, Ties & Trays"},
    {"kw": "how to organize a rental apartment without drilling", "cat": "organization", "type": "howto",
     "title": "How to Organize a Rental Apartment Without Drilling a Single Hole"},
    {"kw": "best no drill storage solutions", "cat": "organization", "type": "comparison",
     "title": "Best No-Drill Storage Solutions for Renters"},
    {"kw": "how to maximize closet space cheaply", "cat": "organization", "type": "howto",
     "title": "How to Maximize Closet Space Cheaply (5 Fixes That Double It)"},
    {"kw": "how to organize a mudroom on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize a Mudroom on a Budget (Even Without a Mudroom)"},
    {"kw": "best cheap entryway storage ideas", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Entryway Storage Ideas: Hooks, Benches & Baskets"},
    {"kw": "how to organize under the sink cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize Under the Sink Cheaply (The Pipes Problem, Solved)"},
    {"kw": "best under sink organizers", "cat": "organization", "type": "comparison",
     "title": "Best Under-Sink Organizers That Fit Around the Pipes"},
    {"kw": "how to organize holiday decorations cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize Holiday Decorations Cheaply (Undo the Tangle)"},
    {"kw": "best cheap ornament storage boxes", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Ornament Storage Boxes (No Broken Baubles)"},
    {"kw": "how to organize a bookshelf beautifully cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Bookshelf Beautifully for Under $20"},
    # --- cleaning ---
    {"kw": "best cheap robot vacuum under $150", "cat": "cleaning", "type": "comparison",
     "title": "Best Robot Vacuums Under $150 in {year}: Worth It or Not?"},
    {"kw": "how to clean a house fast in 30 minutes", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a House Fast: A 30-Minute Routine That Works"},
    {"kw": "best budget steam mop", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Steam Mops: Clean Floors Without Chemicals"},
    {"kw": "how to remove stains with baking soda and vinegar", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Stains with Baking Soda and Vinegar (12 Fixes)"},
    {"kw": "best microfiber cloths value pack", "cat": "cleaning", "type": "comparison",
     "title": "Best Microfiber Cloth Value Packs: Why Cheap Ones Are Fine"},
    {"kw": "best cordless vacuum under $100", "cat": "cleaning", "type": "comparison",
     "title": "Best Cordless Vacuums Under $100 in {year} (Real Tests)"},
    {"kw": "how often should you wash your bedding", "cat": "cleaning", "type": "howto",
     "title": "How Often Should You Wash Your Bedding? A Simple Schedule"},
    {"kw": "cheapest green cleaning products you can make", "cat": "cleaning", "type": "howto",
     "title": "The Cheapest Green Cleaning Products Are the Ones You Make"},
    {"kw": "best budget vacuum for pet hair under $150", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Vacuums for Pet Hair Under $150 (Fur Wars, Won)"},
    {"kw": "best stick vacuum for hardwood floors cheap", "cat": "cleaning", "type": "comparison",
     "title": "Best Stick Vacuums for Hardwood Floors (Budget Picks)"},
    {"kw": "best budget carpet cleaner machine", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Carpet Cleaner Machines: Rugs That Look New"},
    {"kw": "how to clean a couch at home cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Couch at Home Cheaply (No Machine Needed)"},
    {"kw": "how to clean grout with baking soda", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Grout with Baking Soda (Bright Tiles for Pennies)"},
    {"kw": "how to clean an oven without chemicals", "cat": "cleaning", "type": "howto",
     "title": "How to Clean an Oven Without Chemicals (The Baking Soda Paste)"},
    {"kw": "how to clean a microwave fast", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Microwave in 5 Minutes (Steam Trick)"},
    {"kw": "how to clean stainless steel appliances cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Stainless Steel Appliances Cheaply (No Streaks)"},
    {"kw": "how to remove hard water stains cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Hard Water Stains from Glass (The Vinegar Fix)"},
    {"kw": "how to get rid of mildew smell in laundry", "cat": "cleaning", "type": "howto",
     "title": "How to Get Rid of Mildew Smell in Laundry (And Keep It Gone)"},
    {"kw": "how to wash pillows at home", "cat": "cleaning", "type": "howto",
     "title": "How to Wash Pillows at Home (Fluffy, Not Lumpy)"},
    {"kw": "how to clean white sneakers cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean White Sneakers with Baking Soda (Works Every Time)"},
    {"kw": "how to dust a house fast", "cat": "cleaning", "type": "howto",
     "title": "How to Dust a House Fast (Top-Down in 10 Minutes)"},
    {"kw": "how to clean windows without streaks cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Windows Without Streaks (The $2 Solution)"},
    {"kw": "how to deep clean a bedroom in an hour", "cat": "cleaning", "type": "howto",
     "title": "How to Deep Clean a Bedroom in One Hour (Checklist Inside)"},
    {"kw": "best budget mop for hardwood floors", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Mops for Hardwood Floors (Wet, Dry & Spray)"},
    {"kw": "how to clean a washing machine cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Washing Machine Cheaply (Yes, It Needs It)"},
    {"kw": "how to remove pet hair from furniture cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Pet Hair from Furniture (Cheap Tools That Work)"},
    # --- home-office ---
    {"kw": "best budget office chair under $150", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Office Chairs Under $150 in {year} (Back Pain Check)"},
    {"kw": "cheapest standing desk setup", "cat": "home-office", "type": "howto",
     "title": "The Cheapest Standing Desk Setup That Actually Works"},
    {"kw": "best budget desk lamp for eye strain", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Desk Lamps for Eye Strain (Under $40)"},
    {"kw": "how to build a home office on $200", "cat": "home-office", "type": "howto",
     "title": "How to Build a Whole Home Office for $200 (Full Parts List)"},
    {"kw": "best budget monitor under $150", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Monitors Under $150: What to Buy and What to Skip"},
    {"kw": "best cable management ideas on a budget", "cat": "home-office", "type": "howto",
     "title": "Best Cable Management Ideas on a Budget (No Drilling Needed)"},
    {"kw": "best budget laptop stand", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Laptop Stands (Neck Pain Fix for Under $30)"},
    {"kw": "best ergonomic keyboard under $50", "cat": "home-office", "type": "comparison",
     "title": "Best Ergonomic Keyboards Under $50 (Wrists Will Thank You)"},
    {"kw": "best budget wireless mouse", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Wireless Mice (Under $25, Daily Drivers)"},
    {"kw": "best cheap desk organizer", "cat": "home-office", "type": "comparison",
     "title": "Best Cheap Desk Organizers: Clear the Clutter for Under $20"},
    {"kw": "best budget monitor arm", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Monitor Arms (Reclaim Your Desk for Under $50)"},
    {"kw": "how to set up a home office in a bedroom", "cat": "home-office", "type": "howto",
     "title": "How to Set Up a Home Office in a Bedroom (Small Space Playbook)"},
    {"kw": "best small desk for small spaces budget", "cat": "home-office", "type": "comparison",
     "title": "Best Small Desks for Small Spaces (Budget Picks)"},
    {"kw": "best corner desk for home office budget", "cat": "home-office", "type": "comparison",
     "title": "Best Corner Desks for Home Offices (Max Space, Min Cost)"},
    {"kw": "how to reduce eye strain working from home", "cat": "home-office", "type": "howto",
     "title": "How to Reduce Eye Strain Working from Home (The 20-20-20 Fix)"},
    {"kw": "best budget webcam for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Webcams for Work (Look Good on Calls for Under $50)"},
    {"kw": "how to make a home office private without walls", "cat": "home-office", "type": "howto",
     "title": "How to Make a Home Office Private Without Walls (Room Dividers & More)"},
    {"kw": "best budget standing desk converter", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Standing Desk Converters (Stand Up for Under $100)"},
    {"kw": "how to organize a home office desk cheaply", "cat": "home-office", "type": "howto",
     "title": "How to Organize a Home Office Desk Cheaply (The 3-Zone Method)"},
    {"kw": "best budget noise cancelling headphones for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Noise-Cancelling Headphones for Work (Under $80)"},
    {"kw": "how to soundproof a home office cheaply", "cat": "home-office", "type": "howto",
     "title": "How to Soundproof a Home Office Cheaply (10 Real Fixes)"},
    {"kw": "best budget laptop backpack for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Laptop Backpacks for Work (Comfort & Padding)"},
    # --- pet ---
    {"kw": "best budget dog bed that lasts", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Beds That Last (Chewed & Tested)"},
    {"kw": "cheapest way to keep your dog entertained", "cat": "pet", "type": "howto",
     "title": "The Cheapest Ways to Keep Your Dog Entertained (Most Are Free)"},
    {"kw": "best cat scratching post under $30", "cat": "pet", "type": "comparison",
     "title": "Best Cat Scratching Posts Under $30 Your Cat Will Actually Use"},
    {"kw": "how to save money on pet food safely", "cat": "pet", "type": "howto",
     "title": "How to Save Money on Pet Food Without Cutting Corners"},
    {"kw": "best budget cat food that's healthy", "cat": "pet", "type": "comparison",
     "title": "Best Budget Cat Foods That Are Still Healthy (Vet-Approved Picks)"},
    {"kw": "best budget dog food brands", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Food Brands (Nutrition vs Price, Honest Math)"},
    {"kw": "best cheap dog toys that last", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Dog Toys That Last (Power Chewers Welcome)"},
    {"kw": "best indestructible dog toys budget", "cat": "pet", "type": "comparison",
     "title": "Best 'Indestructible' Dog Toys on a Budget (We Tested the Claims)"},
    {"kw": "best cat toys under $10", "cat": "pet", "type": "comparison",
     "title": "Best Cat Toys Under $10 (That Cats Actually Play With)"},
    {"kw": "how to entertain a cat indoors cheaply", "cat": "pet", "type": "howto",
     "title": "How to Entertain an Indoor Cat Cheaply (12 Ideas, Most Free)"},
    {"kw": "best budget cat tree", "cat": "pet", "type": "comparison",
     "title": "Best Budget Cat Trees (Tall, Sturdy & Under $60)"},
    {"kw": "how to groom a dog at home cheaply", "cat": "pet", "type": "howto",
     "title": "How to Groom a Dog at Home Cheaply (Save $50 a Visit)"},
    {"kw": "best budget dog grooming kit", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Grooming Kits (Clippers, Brushes & Nails)"},
    {"kw": "how to trim dog nails at home safely", "cat": "pet", "type": "howto",
     "title": "How to Trim Dog Nails at Home Safely (No Vet Visit Needed)"},
    {"kw": "best budget dog crate", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Crates (Safe, Sturdy & Affordable)"},
    {"kw": "best cheap pet gate for dogs", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Pet Gates for Dogs (Stairs, Doors & Doorways)"},
    {"kw": "how to save on vet bills cheaply", "cat": "pet", "type": "howto",
     "title": "How to Save on Vet Bills (Legally and Safely)"},
    {"kw": "best budget pet camera", "cat": "pet", "type": "comparison",
     "title": "Best Budget Pet Cameras (Check In Without Breaking the Bank)"},
    # --- garden ---
    {"kw": "best budget garden tools for beginners", "cat": "garden", "type": "comparison",
     "title": "Best Budget Garden Tools for Beginners (You Don't Need 50)"},
    {"kw": "how to start a vegetable garden for under $50", "cat": "garden", "type": "howto",
     "title": "How to Start a Vegetable Garden for Under $50 (Step by Step)"},
    {"kw": "cheapest way to build raised garden beds", "cat": "garden", "type": "howto",
     "title": "The Cheapest Way to Build Raised Garden Beds That Last"},
    {"kw": "best indoor plants for low light cheap", "cat": "garden", "type": "comparison",
     "title": "Best Indoor Plants for Low Light (Cheap & Nearly Impossible to Kill)"},
    {"kw": "best budget greenhouse kits", "cat": "garden", "type": "comparison",
     "title": "Best Budget Greenhouse Kits (Grow Year-Round for Less)"},
    {"kw": "how to build a cheap greenhouse", "cat": "garden", "type": "howto",
     "title": "How to Build a Cheap Greenhouse (PVC & Plastic, Under $100)"},
    {"kw": "best budget pruning shears", "cat": "garden", "type": "comparison",
     "title": "Best Budget Pruning Shears (Clean Cuts, No Rust)"},
    {"kw": "how to compost at home cheaply", "cat": "garden", "type": "howto",
     "title": "How to Compost at Home Cheaply (Even in an Apartment)"},
    {"kw": "best cheap compost bin", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Compost Bins (Indoor & Outdoor)"},
    {"kw": "how to grow herbs indoors cheaply", "cat": "garden", "type": "howto",
     "title": "How to Grow Herbs Indoors Cheaply (Window Garden Guide)"},
    {"kw": "best budget grow lights", "cat": "garden", "type": "comparison",
     "title": "Best Budget Grow Lights for Indoor Plants (Under $40)"},
    {"kw": "how to start seeds indoors cheaply", "cat": "garden", "type": "howto",
     "title": "How to Start Seeds Indoors Cheaply (No Fancy Gear Needed)"},
    {"kw": "how to save seeds from vegetables", "cat": "garden", "type": "howto",
     "title": "How to Save Seeds from Vegetables (Free Plants Forever)"},
    {"kw": "best budget watering can", "cat": "garden", "type": "comparison",
     "title": "Best Budget Watering Cans (Light, Durable & Cheap)"},
    {"kw": "how to water plants while on vacation cheaply", "cat": "garden", "type": "howto",
     "title": "How to Water Plants While on Vacation (Cheap DIY Methods)"},
    {"kw": "best cheap plant pots", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Plant Pots (Plastic vs Ceramic vs Fabric)"},
    {"kw": "how to repot plants cheaply", "cat": "garden", "type": "howto",
     "title": "How to Repot Plants Cheaply (And When It's Actually Needed)"},
    {"kw": "best budget hedge trimmers", "cat": "garden", "type": "comparison",
     "title": "Best Budget Hedge Trimmers (Manual vs Electric)"},
    {"kw": "how to mulch cheaply", "cat": "garden", "type": "howto",
     "title": "How to Mulch Cheaply (Free Sources of Mulch You're Ignoring)"},
    {"kw": "best budget garden hose", "cat": "garden", "type": "comparison",
     "title": "Best Budget Garden Hoses (No Kinks, No Leaks, No Drama)"},
    # --- energy ---
    {"kw": "cheapest ways to save on electricity bills", "cat": "energy", "type": "howto",
     "title": "The Cheapest Ways to Save on Electricity Bills (Ranked by Effort)"},
    {"kw": "best smart plugs under $15 to cut energy waste", "cat": "energy", "type": "comparison",
     "title": "Best Smart Plugs Under $15 to Cut Energy Waste"},
    {"kw": "how to lower your heating bill without buying anything", "cat": "energy", "type": "howto",
     "title": "How to Lower Your Heating Bill Without Buying Anything"},
    {"kw": "are cheap LED bulbs worth it", "cat": "energy", "type": "comparison",
     "title": "Are Cheap LED Bulbs Worth It? We Did the Math"},
    {"kw": "best energy efficient space heater under $50", "cat": "energy", "type": "comparison",
     "title": "Best Energy-Efficient Space Heaters Under $50 (Warm Room, Low Bill)"},
    {"kw": "best budget dehumidifier", "cat": "energy", "type": "comparison",
     "title": "Best Budget Dehumidifiers (Moisture Out, Money Saved)"},
    {"kw": "how to cool a room without AC cheaply", "cat": "energy", "type": "howto",
     "title": "How to Cool a Room Without AC (Cheap & Surprisingly Effective)"},
    {"kw": "best cheap fans for summer", "cat": "energy", "type": "comparison",
     "title": "Best Cheap Fans for Summer (Tower, Pedestal & Clip-On)"},
    {"kw": "how to insulate windows cheaply", "cat": "energy", "type": "howto",
     "title": "How to Insulate Windows Cheaply (The Plastic Film Method)"},
    {"kw": "best window insulation kits budget", "cat": "energy", "type": "comparison",
     "title": "Best Window Insulation Kits (Draft-Free Winters for Under $20)"},
    {"kw": "how to save water and lower your bill", "cat": "energy", "type": "howto",
     "title": "How to Save Water and Lower Your Bill (15 Real Changes)"},
    {"kw": "best low flow showerhead", "cat": "energy", "type": "comparison",
     "title": "Best Low-Flow Showerheads (Strong Pressure, Small Bills)"},
    {"kw": "how to reduce water heater costs", "cat": "energy", "type": "howto",
     "title": "How to Reduce Water Heater Costs (5 Easy Wins)"},
    {"kw": "best budget programmable thermostat", "cat": "energy", "type": "comparison",
     "title": "Best Budget Programmable Thermostats (Set It and Save)"},
    {"kw": "how to save on laundry costs", "cat": "energy", "type": "howto",
     "title": "How to Save on Laundry Costs (Energy, Water & Detergent)"},
    {"kw": "how to find energy vampire appliances", "cat": "energy", "type": "howto",
     "title": "How to Find Energy Vampire Appliances (And Slay Them)"},
    {"kw": "best budget ceiling fan with light", "cat": "energy", "type": "comparison",
     "title": "Best Budget Ceiling Fans with Lights (Airflow on a Budget)"},
    # --- tools ---
    {"kw": "best budget power drill", "cat": "tools", "type": "comparison",
     "title": "Best Budget Power Drills (Corded vs Cordless for Beginners)"},
    {"kw": "best cordless drill under $50", "cat": "tools", "type": "comparison",
     "title": "Best Cordless Drills Under $50 (Real Projects, Not Toy Drills)"},
    {"kw": "best budget tool set for home", "cat": "tools", "type": "comparison",
     "title": "Best Budget Tool Sets for Home (The 3 Sets Worth Buying)"},
    {"kw": "best cheap screwdriver set", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Screwdriver Sets (Magnetic Tips Matter)"},
    {"kw": "how to build a basic tool kit cheaply", "cat": "tools", "type": "howto",
     "title": "How to Build a Basic Tool Kit for Under $60 (12 Essentials)"},
    {"kw": "best budget level", "cat": "tools", "type": "comparison",
     "title": "Best Budget Levels (Torpedo, Box & Laser for Less)"},
    {"kw": "best cheap tape measure", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Tape Measures (The 25-Foot Workhorse)"},
    {"kw": "how to fix a leaky faucet cheaply", "cat": "tools", "type": "howto",
     "title": "How to Fix a Leaky Faucet Cheaply (The $5 Repair)"},
    {"kw": "best budget toolbox", "cat": "tools", "type": "comparison",
     "title": "Best Budget Toolboxes (Plastic vs Metal vs Bag)"},
    {"kw": "how to organize tools cheaply", "cat": "tools", "type": "howto",
     "title": "How to Organize Tools Cheaply (Garage & Apartment Versions)"},
    {"kw": "best budget hammer", "cat": "tools", "type": "comparison",
     "title": "Best Budget Hammers (Claw, Framing & Rubber)"},
    {"kw": "how to hang a picture frame straight cheaply", "cat": "tools", "type": "howto",
     "title": "How to Hang a Picture Frame Straight (No Laser Needed)"},
    {"kw": "best budget drill bit set", "cat": "tools", "type": "comparison",
     "title": "Best Budget Drill Bit Sets (Bits That Don't Snap)"},
    {"kw": "how to assemble furniture faster", "cat": "tools", "type": "howto",
     "title": "How to Assemble Flat-Pack Furniture Faster (Pro Tips)"},
]
