"""Built-in keyword / topic pool for ThriftyNest.

Each topic is a dict:
    kw      - the target search phrase (long-tail, low competition)
    title   - article title template (may contain {year})
    cat     - category slug (see build_site.py CATEGORY_NAMES)
    type    - comparison | howto | list

The generator picks topics that have not been written yet and never repeats
them. Add your own topics to this list anytime — the pipeline picks them up
on the next run.
"""

# ============================================================================
# 已与 keywords_extra.py 合并（第二批 239 条，共 428 条）
# 本文件为完全内联版本，不依赖 import，便于直接替换上传。
# ============================================================================

TOPICS = [
    # --- kitchen ---
    {"kw": "best air fryer under $50", "cat": "kitchen", "type": "comparison",
     "title": "The 7 Best Air Fryers Under $50 in {year} (Tested & Compared)"},
    {"kw": "best air fryer for one person", "cat": "kitchen", "type": "comparison",
     "title": "Best Air Fryers for One Person in {year}: Small, Cheap & Quiet"},
    {"kw": "best coffee maker under $100", "cat": "kitchen", "type": "comparison",
     "title": "The 5 Best Coffee Makers Under $100 in {year} (Honest Review)"},
    {"kw": "cheap electric kettle that lasts", "cat": "kitchen", "type": "comparison",
     "title": "5 Cheap Electric Kettles That Actually Last (Under $30)"},
    {"kw": "best meal prep containers that don't leak", "cat": "kitchen", "type": "comparison",
     "title": "Best Meal Prep Containers That Don't Leak or Break (Budget Picks)"},
    {"kw": "best slow cooker under $40", "cat": "kitchen", "type": "comparison",
     "title": "Best Slow Cookers Under $40 in {year}: Set It and Forget It, Cheaply"},
    {"kw": "best rice cooker under $50", "cat": "kitchen", "type": "comparison",
     "title": "Best Rice Cookers Under $50: Foolproof Rice Without the Price Tag"},
    {"kw": "best toaster under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Toasters Under $30 That Actually Toast Evenly"},
    {"kw": "best budget blender for smoothies", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Blenders for Smoothies in {year} (Under $50)"},
    {"kw": "how to stock a budget pantry", "cat": "kitchen", "type": "howto",
     "title": "How to Stock a Budget Pantry: 50 Items for Under $100"},
    {"kw": "cheapest way to cook healthy meals", "cat": "kitchen", "type": "howto",
     "title": "The Cheapest Way to Cook Healthy Meals at Home (Real Numbers)"},
    {"kw": "best budget cookware set", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Cookware Sets in {year}: What's Worth Buying"},
    {"kw": "best air fryer toaster oven combo under $100", "cat": "kitchen", "type": "comparison",
     "title": "Best Air Fryer Toaster Oven Combos Under $100 (Two Appliances, One Price)"},
    {"kw": "best budget air fryer for a family of 4", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Air Fryers for a Family of 4 (Big Baskets, Small Prices)"},
    {"kw": "best cheap french press", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap French Presses: Great Coffee for Under $25"},
    {"kw": "best budget pour over coffee maker", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Pour Over Coffee Makers (Under $40)"},
    {"kw": "best budget electric griddle", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Electric Griddles: Pancake Sundays Without the Price"},
    {"kw": "best waffle maker under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Waffle Makers Under $30 (Crispy, Cheap & Easy to Clean)"},
    {"kw": "best cheap stand mixer alternatives", "cat": "kitchen", "type": "howto",
     "title": "Best Cheap Stand Mixer Alternatives: What to Buy Instead"},
    {"kw": "best hand mixer under $25", "cat": "kitchen", "type": "comparison",
     "title": "Best Hand Mixers Under $25 That Actually Last"},
    {"kw": "best immersion blender under $40", "cat": "kitchen", "type": "comparison",
     "title": "Best Immersion Blenders Under $40 (Soup Season, Solved)"},
    {"kw": "best food processor under $60", "cat": "kitchen", "type": "comparison",
     "title": "Best Food Processors Under $60: Prep Work Without the Price Tag"},
    {"kw": "best budget knives set", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Knife Sets: You Don't Need to Spend $200"},
    {"kw": "best chef knife under $30", "cat": "kitchen", "type": "comparison",
     "title": "Best Chef Knives Under $30 (The Only Knife Most Cooks Need)"},
    {"kw": "best cheap cutting boards", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Cutting Boards: Wood vs Plastic vs Bamboo"},
    {"kw": "best nonstick pan under $25", "cat": "kitchen", "type": "comparison",
     "title": "Best Nonstick Pans Under $25 (That Don't Peel in a Month)"},
    {"kw": "best budget cast iron skillet", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Cast Iron Skillets: The $20 Pan That Lasts Decades"},
    {"kw": "best budget dutch oven", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Dutch Ovens: Le Creuset Looks for Less"},
    {"kw": "best instant pot alternative under $60", "cat": "kitchen", "type": "comparison",
     "title": "Best Instant Pot Alternatives Under $60 (Multicookers That Deliver)"},
    {"kw": "best budget pressure cooker", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Pressure Cookers: Fast Dinners for Less"},
    {"kw": "electric kettle vs stovetop which is cheaper", "cat": "kitchen", "type": "howto",
     "title": "Electric Kettle vs Stovetop: Which Is Actually Cheaper?"},
    {"kw": "how to meal prep on a budget for beginners", "cat": "kitchen", "type": "howto",
     "title": "How to Meal Prep on a Budget: A Beginner's 7-Day Plan"},
    {"kw": "cheap healthy snacks to meal prep", "cat": "kitchen", "type": "list",
     "title": "15 Cheap Healthy Snacks You Can Meal Prep This Weekend"},
    {"kw": "how to save money on groceries every month", "cat": "kitchen", "type": "howto",
     "title": "How to Save Money on Groceries Every Month (14 Tricks That Add Up)"},
    {"kw": "cheapest meals for a family of four", "cat": "kitchen", "type": "list",
     "title": "The 10 Cheapest Meals for a Family of Four (Under $10 Each)"},
    {"kw": "how to reduce food waste at home", "cat": "kitchen", "type": "howto",
     "title": "How to Reduce Food Waste at Home (and Save $100 a Month)"},
    {"kw": "best budget water filter pitcher", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Water Filter Pitchers: Which Filter Actually Filters?"},
    {"kw": "best cheap lunch ideas for work", "cat": "kitchen", "type": "list",
     "title": "12 Cheap Lunch Ideas for Work (No Microwave Required)"},
    {"kw": "best budget toaster oven", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Toaster Ovens: The Mini Oven That Earns Its Spot"},
    {"kw": "how to cook rice perfectly without a rice cooker", "cat": "kitchen", "type": "howto",
     "title": "How to Cook Rice Perfectly Without a Rice Cooker (Stovetop Method)"},
    {"kw": "best budget juicer", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Juicers: Fresh Juice Without the $300 Machine"},
    # --- organization ---
    {"kw": "how to organize a small kitchen on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize a Small Kitchen on a Budget (12 Cheap Tricks)"},
    {"kw": "best cheap storage bins for closets", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Storage Bins for Closets That Actually Look Good"},
    {"kw": "how to declutter your home in a weekend", "cat": "organization", "type": "howto",
     "title": "How to Declutter Your Home in One Weekend (Room-by-Room Plan)"},
    {"kw": "best drawer organizers under $20", "cat": "organization", "type": "comparison",
     "title": "Best Drawer Organizers Under $20 (Kitchen, Desk & Bathroom)"},
    {"kw": "small apartment storage ideas on a budget", "cat": "organization", "type": "howto",
     "title": "Small Apartment Storage Ideas That Cost Almost Nothing"},
    {"kw": "best under-bed storage containers", "cat": "organization", "type": "comparison",
     "title": "Best Under-Bed Storage Containers: Cheap, Durable & Dust-Free"},
    {"kw": "how to organize a tiny bathroom cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Tiny Bathroom Without Spending Much"},
    {"kw": "best closet organizers under $50", "cat": "organization", "type": "comparison",
     "title": "Best Closet Organizers Under $50 (Shelves, Rods & Bins)"},
    {"kw": "garage organization on a budget", "cat": "organization", "type": "howto",
     "title": "Garage Organization on a Budget: Cheap Ideas That Work"},
    {"kw": "best shoe racks for small spaces", "cat": "organization", "type": "comparison",
     "title": "Best Shoe Racks for Small Spaces (Under $30)"},
    {"kw": "how to organize a closet with little space", "cat": "organization", "type": "howto",
     "title": "How to Organize a Closet with Little Space (The 60/40 Rule)"},
    {"kw": "best cheap closet shelf kits", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Closet Shelf Kits: Double Your Hanging Space"},
    {"kw": "how to organize a pantry cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Pantry Cheaply (No Custom Shelving Needed)"},
    {"kw": "best cheap pantry organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Pantry Organizers: Bins, Risers & Labels Under $25"},
    {"kw": "how to organize kids toys on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize Kids' Toys on a Budget (That Kids Can Maintain)"},
    {"kw": "best cheap toy storage ideas", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Toy Storage Ideas for Small Homes"},
    {"kw": "how to organize a laundry room cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Laundry Room Cheaply in an Afternoon"},
    {"kw": "how to organize paper clutter at home", "cat": "organization", "type": "howto",
     "title": "How to Organize Paper Clutter at Home (The 3-Box System)"},
    {"kw": "best cheap file organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap File Organizers for Home Offices"},
    {"kw": "how to organize cables and cords", "cat": "organization", "type": "howto",
     "title": "How to Organize Cables and Cords (The $10 Solution)"},
    {"kw": "best cheap cable organizers", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Cable Organizers: Clips, Ties & Trays"},
    {"kw": "how to organize a rental apartment without drilling", "cat": "organization", "type": "howto",
     "title": "How to Organize a Rental Apartment Without Drilling a Single Hole"},
    {"kw": "best no drill storage solutions", "cat": "organization", "type": "comparison",
     "title": "Best No-Drill Storage Solutions for Renters"},
    {"kw": "how to maximize closet space cheaply", "cat": "organization", "type": "howto",
     "title": "How to Maximize Closet Space Cheaply (5 Fixes That Double It)"},
    {"kw": "how to organize a mudroom on a budget", "cat": "organization", "type": "howto",
     "title": "How to Organize a Mudroom on a Budget (Even Without a Mudroom)"},
    {"kw": "best cheap entryway storage ideas", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Entryway Storage Ideas: Hooks, Benches & Baskets"},
    {"kw": "how to organize under the sink cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize Under the Sink Cheaply (The Pipes Problem, Solved)"},
    {"kw": "best under sink organizers", "cat": "organization", "type": "comparison",
     "title": "Best Under-Sink Organizers That Fit Around the Pipes"},
    {"kw": "how to organize holiday decorations cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize Holiday Decorations Cheaply (Undo the Tangle)"},
    {"kw": "best cheap ornament storage boxes", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Ornament Storage Boxes (No Broken Baubles)"},
    {"kw": "how to organize a bookshelf beautifully cheaply", "cat": "organization", "type": "howto",
     "title": "How to Organize a Bookshelf Beautifully for Under $20"},
    # --- cleaning ---
    {"kw": "best cheap robot vacuum under $150", "cat": "cleaning", "type": "comparison",
     "title": "Best Robot Vacuums Under $150 in {year}: Worth It or Not?"},
    {"kw": "how to clean a house fast in 30 minutes", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a House Fast: A 30-Minute Routine That Works"},
    {"kw": "best budget steam mop", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Steam Mops: Clean Floors Without Chemicals"},
    {"kw": "how to remove stains with baking soda and vinegar", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Stains with Baking Soda and Vinegar (12 Fixes)"},
    {"kw": "best microfiber cloths value pack", "cat": "cleaning", "type": "comparison",
     "title": "Best Microfiber Cloth Value Packs: Why Cheap Ones Are Fine"},
    {"kw": "best cordless vacuum under $100", "cat": "cleaning", "type": "comparison",
     "title": "Best Cordless Vacuums Under $100 in {year} (Real Tests)"},
    {"kw": "how often should you wash your bedding", "cat": "cleaning", "type": "howto",
     "title": "How Often Should You Wash Your Bedding? A Simple Schedule"},
    {"kw": "cheapest green cleaning products you can make", "cat": "cleaning", "type": "howto",
     "title": "The Cheapest Green Cleaning Products Are the Ones You Make"},
    {"kw": "best budget vacuum for pet hair under $150", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Vacuums for Pet Hair Under $150 (Fur Wars, Won)"},
    {"kw": "best stick vacuum for hardwood floors cheap", "cat": "cleaning", "type": "comparison",
     "title": "Best Stick Vacuums for Hardwood Floors (Budget Picks)"},
    {"kw": "best budget carpet cleaner machine", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Carpet Cleaner Machines: Rugs That Look New"},
    {"kw": "how to clean a couch at home cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Couch at Home Cheaply (No Machine Needed)"},
    {"kw": "how to clean grout with baking soda", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Grout with Baking Soda (Bright Tiles for Pennies)"},
    {"kw": "how to clean an oven without chemicals", "cat": "cleaning", "type": "howto",
     "title": "How to Clean an Oven Without Chemicals (The Baking Soda Paste)"},
    {"kw": "how to clean a microwave fast", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Microwave in 5 Minutes (Steam Trick)"},
    {"kw": "how to clean stainless steel appliances cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Stainless Steel Appliances Cheaply (No Streaks)"},
    {"kw": "how to remove hard water stains cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Hard Water Stains from Glass (The Vinegar Fix)"},
    {"kw": "how to get rid of mildew smell in laundry", "cat": "cleaning", "type": "howto",
     "title": "How to Get Rid of Mildew Smell in Laundry (And Keep It Gone)"},
    {"kw": "how to wash pillows at home", "cat": "cleaning", "type": "howto",
     "title": "How to Wash Pillows at Home (Fluffy, Not Lumpy)"},
    {"kw": "how to clean white sneakers cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean White Sneakers with Baking Soda (Works Every Time)"},
    {"kw": "how to dust a house fast", "cat": "cleaning", "type": "howto",
     "title": "How to Dust a House Fast (Top-Down in 10 Minutes)"},
    {"kw": "how to clean windows without streaks cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Windows Without Streaks (The $2 Solution)"},
    {"kw": "how to deep clean a bedroom in an hour", "cat": "cleaning", "type": "howto",
     "title": "How to Deep Clean a Bedroom in One Hour (Checklist Inside)"},
    {"kw": "best budget mop for hardwood floors", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Mops for Hardwood Floors (Wet, Dry & Spray)"},
    {"kw": "how to clean a washing machine cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Washing Machine Cheaply (Yes, It Needs It)"},
    {"kw": "how to remove pet hair from furniture cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Pet Hair from Furniture (Cheap Tools That Work)"},
    # --- home-office ---
    {"kw": "best budget office chair under $150", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Office Chairs Under $150 in {year} (Back Pain Check)"},
    {"kw": "cheapest standing desk setup", "cat": "home-office", "type": "howto",
     "title": "The Cheapest Standing Desk Setup That Actually Works"},
    {"kw": "best budget desk lamp for eye strain", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Desk Lamps for Eye Strain (Under $40)"},
    {"kw": "how to build a home office on $200", "cat": "home-office", "type": "howto",
     "title": "How to Build a Whole Home Office for $200 (Full Parts List)"},
    {"kw": "best budget monitor under $150", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Monitors Under $150: What to Buy and What to Skip"},
    {"kw": "best cable management ideas on a budget", "cat": "home-office", "type": "howto",
     "title": "Best Cable Management Ideas on a Budget (No Drilling Needed)"},
    {"kw": "best budget laptop stand", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Laptop Stands (Neck Pain Fix for Under $30)"},
    {"kw": "best ergonomic keyboard under $50", "cat": "home-office", "type": "comparison",
     "title": "Best Ergonomic Keyboards Under $50 (Wrists Will Thank You)"},
    {"kw": "best budget wireless mouse", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Wireless Mice (Under $25, Daily Drivers)"},
    {"kw": "best cheap desk organizer", "cat": "home-office", "type": "comparison",
     "title": "Best Cheap Desk Organizers: Clear the Clutter for Under $20"},
    {"kw": "best budget monitor arm", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Monitor Arms (Reclaim Your Desk for Under $50)"},
    {"kw": "how to set up a home office in a bedroom", "cat": "home-office", "type": "howto",
     "title": "How to Set Up a Home Office in a Bedroom (Small Space Playbook)"},
    {"kw": "best small desk for small spaces budget", "cat": "home-office", "type": "comparison",
     "title": "Best Small Desks for Small Spaces (Budget Picks)"},
    {"kw": "best corner desk for home office budget", "cat": "home-office", "type": "comparison",
     "title": "Best Corner Desks for Home Offices (Max Space, Min Cost)"},
    {"kw": "how to reduce eye strain working from home", "cat": "home-office", "type": "howto",
     "title": "How to Reduce Eye Strain Working from Home (The 20-20-20 Fix)"},
    {"kw": "best budget webcam for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Webcams for Work (Look Good on Calls for Under $50)"},
    {"kw": "how to make a home office private without walls", "cat": "home-office", "type": "howto",
     "title": "How to Make a Home Office Private Without Walls (Room Dividers & More)"},
    {"kw": "best budget standing desk converter", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Standing Desk Converters (Stand Up for Under $100)"},
    {"kw": "how to organize a home office desk cheaply", "cat": "home-office", "type": "howto",
     "title": "How to Organize a Home Office Desk Cheaply (The 3-Zone Method)"},
    {"kw": "best budget noise cancelling headphones for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Noise-Cancelling Headphones for Work (Under $80)"},
    {"kw": "how to soundproof a home office cheaply", "cat": "home-office", "type": "howto",
     "title": "How to Soundproof a Home Office Cheaply (10 Real Fixes)"},
    {"kw": "best budget laptop backpack for work", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Laptop Backpacks for Work (Comfort & Padding)"},
    # --- pet ---
    {"kw": "best budget dog bed that lasts", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Beds That Last (Chewed & Tested)"},
    {"kw": "cheapest way to keep your dog entertained", "cat": "pet", "type": "howto",
     "title": "The Cheapest Ways to Keep Your Dog Entertained (Most Are Free)"},
    {"kw": "best cat scratching post under $30", "cat": "pet", "type": "comparison",
     "title": "Best Cat Scratching Posts Under $30 Your Cat Will Actually Use"},
    {"kw": "how to save money on pet food safely", "cat": "pet", "type": "howto",
     "title": "How to Save Money on Pet Food Without Cutting Corners"},
    {"kw": "best budget cat food that's healthy", "cat": "pet", "type": "comparison",
     "title": "Best Budget Cat Foods That Are Still Healthy (Vet-Approved Picks)"},
    {"kw": "best budget dog food brands", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Food Brands (Nutrition vs Price, Honest Math)"},
    {"kw": "best cheap dog toys that last", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Dog Toys That Last (Power Chewers Welcome)"},
    {"kw": "best indestructible dog toys budget", "cat": "pet", "type": "comparison",
     "title": "Best 'Indestructible' Dog Toys on a Budget (We Tested the Claims)"},
    {"kw": "best cat toys under $10", "cat": "pet", "type": "comparison",
     "title": "Best Cat Toys Under $10 (That Cats Actually Play With)"},
    {"kw": "how to entertain a cat indoors cheaply", "cat": "pet", "type": "howto",
     "title": "How to Entertain an Indoor Cat Cheaply (12 Ideas, Most Free)"},
    {"kw": "best budget cat tree", "cat": "pet", "type": "comparison",
     "title": "Best Budget Cat Trees (Tall, Sturdy & Under $60)"},
    {"kw": "how to groom a dog at home cheaply", "cat": "pet", "type": "howto",
     "title": "How to Groom a Dog at Home Cheaply (Save $50 a Visit)"},
    {"kw": "best budget dog grooming kit", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Grooming Kits (Clippers, Brushes & Nails)"},
    {"kw": "how to trim dog nails at home safely", "cat": "pet", "type": "howto",
     "title": "How to Trim Dog Nails at Home Safely (No Vet Visit Needed)"},
    {"kw": "best budget dog crate", "cat": "pet", "type": "comparison",
     "title": "Best Budget Dog Crates (Safe, Sturdy & Affordable)"},
    {"kw": "best cheap pet gate for dogs", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Pet Gates for Dogs (Stairs, Doors & Doorways)"},
    {"kw": "how to save on vet bills cheaply", "cat": "pet", "type": "howto",
     "title": "How to Save on Vet Bills (Legally and Safely)"},
    {"kw": "best budget pet camera", "cat": "pet", "type": "comparison",
     "title": "Best Budget Pet Cameras (Check In Without Breaking the Bank)"},
    # --- garden ---
    {"kw": "best budget garden tools for beginners", "cat": "garden", "type": "comparison",
     "title": "Best Budget Garden Tools for Beginners (You Don't Need 50)"},
    {"kw": "how to start a vegetable garden for under $50", "cat": "garden", "type": "howto",
     "title": "How to Start a Vegetable Garden for Under $50 (Step by Step)"},
    {"kw": "cheapest way to build raised garden beds", "cat": "garden", "type": "howto",
     "title": "The Cheapest Way to Build Raised Garden Beds That Last"},
    {"kw": "best indoor plants for low light cheap", "cat": "garden", "type": "comparison",
     "title": "Best Indoor Plants for Low Light (Cheap & Nearly Impossible to Kill)"},
    {"kw": "best budget greenhouse kits", "cat": "garden", "type": "comparison",
     "title": "Best Budget Greenhouse Kits (Grow Year-Round for Less)"},
    {"kw": "how to build a cheap greenhouse", "cat": "garden", "type": "howto",
     "title": "How to Build a Cheap Greenhouse (PVC & Plastic, Under $100)"},
    {"kw": "best budget pruning shears", "cat": "garden", "type": "comparison",
     "title": "Best Budget Pruning Shears (Clean Cuts, No Rust)"},
    {"kw": "how to compost at home cheaply", "cat": "garden", "type": "howto",
     "title": "How to Compost at Home Cheaply (Even in an Apartment)"},
    {"kw": "best cheap compost bin", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Compost Bins (Indoor & Outdoor)"},
    {"kw": "how to grow herbs indoors cheaply", "cat": "garden", "type": "howto",
     "title": "How to Grow Herbs Indoors Cheaply (Window Garden Guide)"},
    {"kw": "best budget grow lights", "cat": "garden", "type": "comparison",
     "title": "Best Budget Grow Lights for Indoor Plants (Under $40)"},
    {"kw": "how to start seeds indoors cheaply", "cat": "garden", "type": "howto",
     "title": "How to Start Seeds Indoors Cheaply (No Fancy Gear Needed)"},
    {"kw": "how to save seeds from vegetables", "cat": "garden", "type": "howto",
     "title": "How to Save Seeds from Vegetables (Free Plants Forever)"},
    {"kw": "best budget watering can", "cat": "garden", "type": "comparison",
     "title": "Best Budget Watering Cans (Light, Durable & Cheap)"},
    {"kw": "how to water plants while on vacation cheaply", "cat": "garden", "type": "howto",
     "title": "How to Water Plants While on Vacation (Cheap DIY Methods)"},
    {"kw": "best cheap plant pots", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Plant Pots (Plastic vs Ceramic vs Fabric)"},
    {"kw": "how to repot plants cheaply", "cat": "garden", "type": "howto",
     "title": "How to Repot Plants Cheaply (And When It's Actually Needed)"},
    {"kw": "best budget hedge trimmers", "cat": "garden", "type": "comparison",
     "title": "Best Budget Hedge Trimmers (Manual vs Electric)"},
    {"kw": "how to mulch cheaply", "cat": "garden", "type": "howto",
     "title": "How to Mulch Cheaply (Free Sources of Mulch You're Ignoring)"},
    {"kw": "best budget garden hose", "cat": "garden", "type": "comparison",
     "title": "Best Budget Garden Hoses (No Kinks, No Leaks, No Drama)"},
    # --- energy ---
    {"kw": "cheapest ways to save on electricity bills", "cat": "energy", "type": "howto",
     "title": "The Cheapest Ways to Save on Electricity Bills (Ranked by Effort)"},
    {"kw": "best smart plugs under $15 to cut energy waste", "cat": "energy", "type": "comparison",
     "title": "Best Smart Plugs Under $15 to Cut Energy Waste"},
    {"kw": "how to lower your heating bill without buying anything", "cat": "energy", "type": "howto",
     "title": "How to Lower Your Heating Bill Without Buying Anything"},
    {"kw": "are cheap LED bulbs worth it", "cat": "energy", "type": "comparison",
     "title": "Are Cheap LED Bulbs Worth It? We Did the Math"},
    {"kw": "best energy efficient space heater under $50", "cat": "energy", "type": "comparison",
     "title": "Best Energy-Efficient Space Heaters Under $50 (Warm Room, Low Bill)"},
    {"kw": "best budget dehumidifier", "cat": "energy", "type": "comparison",
     "title": "Best Budget Dehumidifiers (Moisture Out, Money Saved)"},
    {"kw": "how to cool a room without AC cheaply", "cat": "energy", "type": "howto",
     "title": "How to Cool a Room Without AC (Cheap & Surprisingly Effective)"},
    {"kw": "best cheap fans for summer", "cat": "energy", "type": "comparison",
     "title": "Best Cheap Fans for Summer (Tower, Pedestal & Clip-On)"},
    {"kw": "how to insulate windows cheaply", "cat": "energy", "type": "howto",
     "title": "How to Insulate Windows Cheaply (The Plastic Film Method)"},
    {"kw": "best window insulation kits budget", "cat": "energy", "type": "comparison",
     "title": "Best Window Insulation Kits (Draft-Free Winters for Under $20)"},
    {"kw": "how to save water and lower your bill", "cat": "energy", "type": "howto",
     "title": "How to Save Water and Lower Your Bill (15 Real Changes)"},
    {"kw": "best low flow showerhead", "cat": "energy", "type": "comparison",
     "title": "Best Low-Flow Showerheads (Strong Pressure, Small Bills)"},
    {"kw": "how to reduce water heater costs", "cat": "energy", "type": "howto",
     "title": "How to Reduce Water Heater Costs (5 Easy Wins)"},
    {"kw": "best budget programmable thermostat", "cat": "energy", "type": "comparison",
     "title": "Best Budget Programmable Thermostats (Set It and Save)"},
    {"kw": "how to save on laundry costs", "cat": "energy", "type": "howto",
     "title": "How to Save on Laundry Costs (Energy, Water & Detergent)"},
    {"kw": "how to find energy vampire appliances", "cat": "energy", "type": "howto",
     "title": "How to Find Energy Vampire Appliances (And Slay Them)"},
    {"kw": "best budget ceiling fan with light", "cat": "energy", "type": "comparison",
     "title": "Best Budget Ceiling Fans with Lights (Airflow on a Budget)"},
    # --- tools ---
    {"kw": "best budget power drill", "cat": "tools", "type": "comparison",
     "title": "Best Budget Power Drills (Corded vs Cordless for Beginners)"},
    {"kw": "best cordless drill under $50", "cat": "tools", "type": "comparison",
     "title": "Best Cordless Drills Under $50 (Real Projects, Not Toy Drills)"},
    {"kw": "best budget tool set for home", "cat": "tools", "type": "comparison",
     "title": "Best Budget Tool Sets for Home (The 3 Sets Worth Buying)"},
    {"kw": "best cheap screwdriver set", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Screwdriver Sets (Magnetic Tips Matter)"},
    {"kw": "how to build a basic tool kit cheaply", "cat": "tools", "type": "howto",
     "title": "How to Build a Basic Tool Kit for Under $60 (12 Essentials)"},
    {"kw": "best budget level", "cat": "tools", "type": "comparison",
     "title": "Best Budget Levels (Torpedo, Box & Laser for Less)"},
    {"kw": "best cheap tape measure", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Tape Measures (The 25-Foot Workhorse)"},
    {"kw": "how to fix a leaky faucet cheaply", "cat": "tools", "type": "howto",
     "title": "How to Fix a Leaky Faucet Cheaply (The $5 Repair)"},
    {"kw": "best budget toolbox", "cat": "tools", "type": "comparison",
     "title": "Best Budget Toolboxes (Plastic vs Metal vs Bag)"},
    {"kw": "how to organize tools cheaply", "cat": "tools", "type": "howto",
     "title": "How to Organize Tools Cheaply (Garage & Apartment Versions)"},
    {"kw": "best budget hammer", "cat": "tools", "type": "comparison",
     "title": "Best Budget Hammers (Claw, Framing & Rubber)"},
    {"kw": "how to hang a picture frame straight cheaply", "cat": "tools", "type": "howto",
     "title": "How to Hang a Picture Frame Straight (No Laser Needed)"},
    {"kw": "best budget drill bit set", "cat": "tools", "type": "comparison",
     "title": "Best Budget Drill Bit Sets (Bits That Don't Snap)"},
    {"kw": "how to assemble furniture faster", "cat": "tools", "type": "howto",
     "title": "How to Assemble Flat-Pack Furniture Faster (Pro Tips)"},

    # ===================== 第二批（keywords_extra，239 条）=====================

    # ===================================================================
    # KITCHEN & COOKING  (kitchen)
    # ===================================================================
    # --- 新增意图：X vs Y（对比决策，转化率最高的类型之一）---
    {"kw": "air fryer vs toaster oven for one person", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Air Fryer vs Toaster Oven for One Person: Which Wins in {year}?"},
    {"kw": "instant pot vs slow cooker for a family", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Instant Pot vs Slow Cooker for a Family: Honest {year} Comparison"},
    {"kw": "cast iron vs nonstick pan for beginners", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Cast Iron vs Nonstick: Which Pan Should a Beginner Buy in {year}?"},
    {"kw": "french press vs drip coffee maker cost", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "French Press vs Drip Coffee Maker: Which Is Cheaper to Own?"},
    {"kw": "rice cooker vs instant pot which is cheaper", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Rice Cooker vs Instant Pot: Which Is Actually Cheaper to Own?"},
    {"kw": "hand mixer vs stand mixer for small kitchens", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Hand Mixer vs Stand Mixer in a Small Kitchen: What to Buy"},
    {"kw": "stainless steel vs nonstick cookware for budget cooks", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Stainless Steel vs Nonstick Cookware on a Budget: The Real Trade-off"},
    {"kw": "electric kettle vs microwave for boiling water cost", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Electric Kettle vs Microwave: Which Boils Water Cheaper?"},
    {"kw": "wood vs plastic cutting boards for cheap kitchens", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Wood vs Plastic Cutting Boards: What's Best on a Budget?"},
    {"kw": "griddle vs skillet for small apartments", "cat": "kitchen", "type": "comparison",
     "intent": "vs",
     "title": "Electric Griddle vs Skillet for a Small Apartment: Which to Buy"},

    # --- 新增意图：is X worth it（决策末期，转化极高）---
    {"kw": "is an air fryer worth it for one person", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is an Air Fryer Worth It for One Person? An Honest {year} Answer"},
    {"kw": "is a bread maker worth it for a family", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Bread Maker Worth It? Real Math for a Family in {year}"},
    {"kw": "is a stand mixer worth the money", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Stand Mixer Worth the Money, or Is a Hand Mixer Enough?"},
    {"kw": "is a food processor worth it if you cook every day", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Food Processor Worth It If You Cook Every Day?"},
    {"kw": "is a slow cooker worth it in a small kitchen", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Slow Cooker Worth the Counter Space in a Small Kitchen?"},
    {"kw": "is a dishwasher worth it for two people", "cat": "kitchen", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Countertop Dishwasher Worth It for Two People?"},

    # --- 新增意图：why is my X <问题>（易排名 + 天然可内链产品页）---
    {"kw": "why is my air fryer smoking", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Air Fryer Smoking? 6 Causes and How to Fix Them"},
    {"kw": "why is my nonstick pan peeling", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Nonstick Pan Peeling? Causes and Fixes That Work"},
    {"kw": "why does my rice cooker overflow", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Rice Cooker Overflow? Easy Fixes for Any Model"},
    {"kw": "why is my kettle so loud", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Electric Kettle So Loud (and Can I Quiet It Down)?"},
    {"kw": "why does my blender smell like burning", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Blender Smell Like Burning? When to Worry"},
    {"kw": "why is my cast iron sticky after seasoning", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Cast Iron Sticky After Seasoning? How to Fix It"},
    {"kw": "why does my microwave spark", "cat": "kitchen", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Microwave Spark? Common Causes and Safe Fixes"},

    # --- 新增意图：how much does X cost（高意图信息词）---
    {"kw": "how much does it cost to run an air fryer", "cat": "kitchen", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Run an Air Fryer? Real Numbers"},
    {"kw": "how much does it cost to run a slow cooker for 8 hours", "cat": "kitchen", "type": "howto",
     "intent": "cost",
     "title": "How Much Does a Slow Cooker Cost to Run for 8 Hours?"},
    {"kw": "how much does it cost to run a dishwasher", "cat": "kitchen", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Run a Dishwasher Per Load?"},

    # --- 场景型 best X for <场景> ---
    {"kw": "best budget pots and pans for a first apartment", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Pots and Pans for a First Apartment in {year}"},
    {"kw": "best cheap kitchen tools for dorm cooking", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Kitchen Tools for Dorm Cooking (No Stove Needed)"},
    {"kw": "best budget cookware for an induction cooktop", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Cookware for Induction Cooktops in {year}"},
    {"kw": "best cheap knife for a small kitchen", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "The Best Cheap Knife for a Small Kitchen (One Knife, Done)"},
    {"kw": "best budget meal prep tools for one person", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Meal Prep Tools for One Person in {year}"},
    {"kw": "best cheap coffee gear for renters", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Coffee Gear for Renters (No Drilling, No Fuss)"},

    # --- 常规 howto / comparison ---
    {"kw": "how to cook dried beans in a slow cooker cheaply", "cat": "kitchen", "type": "howto",
     "title": "How to Cook Dried Beans in a Slow Cooker and Save a Fortune"},
    {"kw": "how to season a cast iron skillet on a budget", "cat": "kitchen", "type": "howto",
     "title": "How to Season a Cast Iron Skillet (Cheap Method That Lasts)"},
    {"kw": "how to sharpen kitchen knives without a sharpener", "cat": "kitchen", "type": "howto",
     "title": "How to Sharpen Kitchen Knives Without Buying a Sharpener"},
    {"kw": "how to stop food from sticking to stainless steel", "cat": "kitchen", "type": "howto",
     "title": "How to Stop Food From Sticking to Stainless Steel Pans"},
    {"kw": "how to organize a freezer to waste less food", "cat": "kitchen", "type": "howto",
     "title": "How to Organize Your Freezer So You Stop Wasting Food"},
    {"kw": "best cheap microwave for a small kitchen", "cat": "kitchen", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Microwaves for a Small Kitchen in {year}"},
    {"kw": "best cheap blender for soups not smoothies", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Blenders for Soup (Not Just Smoothies)"},
    {"kw": "best budget induction cooktop for small kitchens", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Induction Cooktops for Small Kitchens"},
    {"kw": "best cheap water filter pitcher", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Water Filter Pitchers That Actually Work"},
    {"kw": "best budget kitchen scale for baking", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Kitchen Scales for Baking in {year}"},
    {"kw": "best cheap food storage containers for leftovers", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Food Storage Containers for Leftovers"},
    {"kw": "best budget coffee grinder under 40", "cat": "kitchen", "type": "comparison",
     "title": "Best Budget Coffee Grinders Under $40 in {year}"},
    {"kw": "best cheap tea kettle with temperature control", "cat": "kitchen", "type": "comparison",
     "title": "Best Cheap Tea Kettles With Temperature Control"},
    {"kw": "cheapest way to equip a kitchen from scratch", "cat": "kitchen", "type": "list",
     "title": "The Cheapest Way to Equip a Kitchen From Scratch ($200 Total)"},
    {"kw": "cheap pantry staples that save money every week", "cat": "kitchen", "type": "list",
     "title": "15 Cheap Pantry Staples That Save Money Every Single Week"},

    # ===================================================================
    # ORGANIZATION & STORAGE  (organization)
    # ===================================================================
    {"kw": "wire shelving vs closet system for renters", "cat": "organization", "type": "comparison",
     "intent": "vs",
     "title": "Wire Shelving vs a Closet System: What Renters Should Buy"},
    {"kw": "open shelving vs closed cabinets for small kitchens", "cat": "organization", "type": "comparison",
     "intent": "vs",
     "title": "Open Shelving vs Closed Cabinets in a Small Kitchen"},
    {"kw": "plastic vs fabric storage bins for closets", "cat": "organization", "type": "comparison",
     "intent": "vs",
     "title": "Plastic vs Fabric Storage Bins: Which Lasts in a Closet?"},
    {"kw": "is a closet system worth it for a rental", "cat": "organization", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Closet System Worth It in a Rental? (Or Just Use Bins)"},
    {"kw": "is a label maker worth it for home organization", "cat": "organization", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Label Maker Worth It for Home Organization?"},
    {"kw": "why do my closets still feel crowded after organizing", "cat": "organization", "type": "howto",
     "intent": "problem",
     "title": "Why Your Closets Still Feel Crowded After Organizing"},
    {"kw": "why do storage bins crack in the cold", "cat": "organization", "type": "howto",
     "intent": "problem",
     "title": "Why Storage Bins Crack in a Cold Garage (and What to Buy)"},
    {"kw": "how much do closet organizers cost per foot", "cat": "organization", "type": "howto",
     "intent": "cost",
     "title": "How Much Do Closet Organizers Cost Per Foot of Closet"},
    {"kw": "best budget shoe storage for a small entryway", "cat": "organization", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Shoe Storage for a Small Entryway"},
    {"kw": "best cheap storage for a studio apartment", "cat": "organization", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Storage Ideas for a Studio Apartment in {year}"},
    {"kw": "best budget storage for a rented room", "cat": "organization", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Storage Solutions for a Rented Room (No Drills)"},
    {"kw": "best cheap garage shelving that holds real weight", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Garage Shelving That Actually Holds Weight"},
    {"kw": "best budget over the door organizers", "cat": "organization", "type": "comparison",
     "title": "Best Budget Over-the-Door Organizers for Every Room"},
    {"kw": "best cheap vacuum storage bags for bedding", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Vacuum Storage Bags for Bedding and Coats"},
    {"kw": "best budget laundry room organizers", "cat": "organization", "type": "comparison",
     "title": "Best Budget Laundry Room Organizers Under $50"},
    {"kw": "best cheap pantry labels and containers set", "cat": "organization", "type": "comparison",
     "title": "Best Cheap Pantry Labels and Container Sets in {year}"},
    {"kw": "how to organize a linen closet so it stays neat", "cat": "organization", "type": "howto",
     "title": "How to Organize a Linen Closet So It Actually Stays Neat"},
    {"kw": "how to store seasonal clothes without a closet", "cat": "organization", "type": "howto",
     "title": "How to Store Seasonal Clothes When You Have No Closet"},
    {"kw": "how to organize a pantry with deep shelves", "cat": "organization", "type": "howto",
     "title": "How to Organize a Pantry With Deep Shelves (Stop Losing Food)"},
    {"kw": "how to organize tools in a small apartment", "cat": "organization", "type": "howto",
     "title": "How to Organize Tools in a Small Apartment"},
    {"kw": "how to keep a small closet tidy with kids", "cat": "organization", "type": "howto",
     "title": "How to Keep a Small Closet Tidy When You Have Kids"},
    {"kw": "how to organize a coat closet for a family of four", "cat": "organization", "type": "howto",
     "title": "How to Organize a Coat Closet for a Family of Four"},
    {"kw": "how to declutter a garage in one weekend", "cat": "organization", "type": "howto",
     "title": "How to Declutter a Garage in One Weekend (Realistic Plan)"},
    {"kw": "how to organize cleaning supplies safely with pets", "cat": "organization", "type": "howto",
     "title": "How to Organize Cleaning Supplies Safely When You Have Pets"},
    {"kw": "cheap DIY closet shelving ideas that look good", "cat": "organization", "type": "list",
     "title": "12 Cheap DIY Closet Shelving Ideas That Still Look Good"},
    {"kw": "cheapest way to add storage to a rental kitchen", "cat": "organization", "type": "list",
     "title": "The Cheapest Way to Add Storage to a Rental Kitchen"},
    {"kw": "cheap under bed storage ideas that work", "cat": "organization", "type": "list",
     "title": "11 Cheap Under-Bed Storage Ideas That Actually Work"},
    {"kw": "small apartment entryway ideas on a tight budget", "cat": "organization", "type": "list",
     "title": "Small Apartment Entryway Ideas on a Tight Budget"},
    {"kw": "how to organize a mudroom without building one", "cat": "organization", "type": "howto",
     "title": "How to Organize a Mudroom Without Actually Building One"},

    # ===================================================================
    # CLEANING  (cleaning)
    # ===================================================================
    {"kw": "steam mop vs regular mop for hardwood", "cat": "cleaning", "type": "comparison",
     "intent": "vs",
     "title": "Steam Mop vs Regular Mop for Hardwood Floors: Which Is Safe?"},
    {"kw": "microfiber vs cotton cloths for dusting", "cat": "cleaning", "type": "comparison",
     "intent": "vs",
     "title": "Microfiber vs Cotton Cloths: Which Cleans Better for Less?"},
    {"kw": "vinegar vs bleach for cleaning bathrooms", "cat": "cleaning", "type": "comparison",
     "intent": "vs",
     "title": "Vinegar vs Bleach in the Bathroom: Which, When, and Never"},
    {"kw": "is a steam cleaner worth it for home use", "cat": "cleaning", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Steam Cleaner Worth It for Normal Home Use?"},
    {"kw": "is a robot vacuum worth it for pet hair", "cat": "cleaning", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Robot Vacuum Worth It for Pet Hair? Honest Answer"},
    {"kw": "is a carpet cleaner worth renting versus buying", "cat": "cleaning", "type": "comparison",
     "intent": "worthit",
     "title": "Carpet Cleaner: Rent It or Buy It? (Do the Math First)"},
    {"kw": "why does my mop leave streaks", "cat": "cleaning", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Mop Leave Streaks? 5 Fixes That Work"},
    {"kw": "why does my washing machine smell musty", "cat": "cleaning", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Washing Machine Smell Musty? Fix It for Good"},
    {"kw": "why does my shower curtain get pink slime", "cat": "cleaning", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Shower Curtain Get Pink Slime? (and How to Stop It)"},
    {"kw": "why does my vacuum lose suction", "cat": "cleaning", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Vacuum Lose Suction? Check These 5 Things"},
    {"kw": "why are my windows still streaky after cleaning", "cat": "cleaning", "type": "howto",
     "intent": "problem",
     "title": "Why Your Windows Are Still Streaky After Cleaning"},
    {"kw": "how much does it cost to make your own cleaning spray", "cat": "cleaning", "type": "howto",
     "intent": "cost",
     "title": "How Much Does Homemade Cleaning Spray Cost vs Store-Bought?"},
    {"kw": "how much does a cleaning service cost per visit", "cat": "cleaning", "type": "howto",
     "intent": "cost",
     "title": "How Much Does a House Cleaning Service Cost Per Visit?"},
    {"kw": "best cheap mop for tile floors", "cat": "cleaning", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Mops for Tile Floors in {year}"},
    {"kw": "best budget vacuum for a small apartment", "cat": "cleaning", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Vacuums for a Small Apartment"},
    {"kw": "best cheap cleaning tools for a first apartment", "cat": "cleaning", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Cleaning Tools for a First Apartment"},
    {"kw": "best budget carpet cleaner for pet stains", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Carpet Cleaners for Pet Stains in {year}"},
    {"kw": "best cheap squeegee for shower glass", "cat": "cleaning", "type": "comparison",
     "title": "Best Cheap Squeegees for Shower Glass (No More Spots)"},
    {"kw": "best budget duster for high ceilings", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Dusters for High Ceilings and Ceiling Fans"},
    {"kw": "best cheap drain cleaner that actually works", "cat": "cleaning", "type": "comparison",
     "title": "Best Cheap Drain Cleaners That Actually Work"},
    {"kw": "best budget grout brush and cleaner", "cat": "cleaning", "type": "comparison",
     "title": "Best Budget Grout Brushes and Cleaners (Before You Regrout)"},
    {"kw": "how to clean a stainless steel sink cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Stainless Steel Sink Cheaply (No Scratches)"},
    {"kw": "how to clean a dishwasher without buying tablets", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Your Dishwasher Without Buying Tablets"},
    {"kw": "how to remove soap scum without harsh chemicals", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Soap Scum Without Harsh Chemicals"},
    {"kw": "how to clean blinds quickly", "cat": "cleaning", "type": "howto",
     "title": "How to Clean Blinds Quickly (The Sock Method)"},
    {"kw": "how to remove pet urine smell from carpet cheaply", "cat": "cleaning", "type": "howto",
     "title": "How to Remove Pet Urine Smell From Carpet Cheaply"},
    {"kw": "how to clean a mattress without a machine", "cat": "cleaning", "type": "howto",
     "title": "How to Clean a Mattress Without a Machine"},
    {"kw": "how to keep a bathroom clean with less effort", "cat": "cleaning", "type": "howto",
     "title": "How to Keep a Bathroom Clean With Less Effort Each Week"},
    {"kw": "cheapest cleaning supplies that actually work", "cat": "cleaning", "type": "list",
     "title": "8 Cheapest Cleaning Supplies That Actually Work"},
    {"kw": "cheap ways to make a house smell clean", "cat": "cleaning", "type": "list",
     "title": "9 Cheap Ways to Make Your House Smell Clean"},

    # ===================================================================
    # HOME OFFICE  (home-office)
    # ===================================================================
    {"kw": "standing desk vs sitting desk for small spaces", "cat": "home-office", "type": "comparison",
     "intent": "vs",
     "title": "Standing Desk vs Sitting Desk in a Small Space"},
    {"kw": "mechanical vs membrane keyboard for budget offices", "cat": "home-office", "type": "comparison",
     "intent": "vs",
     "title": "Mechanical vs Membrane Keyboards on a Budget: Which to Buy"},
    {"kw": "monitor arm vs monitor stand for a small desk", "cat": "home-office", "type": "comparison",
     "intent": "vs",
     "title": "Monitor Arm vs Monitor Stand on a Small Desk"},
    {"kw": "ring light vs desk lamp for video calls", "cat": "home-office", "type": "comparison",
     "intent": "vs",
     "title": "Ring Light vs Desk Lamp for Video Calls: What Looks Better?"},
    {"kw": "is a standing desk converter worth it", "cat": "home-office", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Standing Desk Converter Worth It, or Just Buy a Desk?"},
    {"kw": "is a second monitor worth it for work from home", "cat": "home-office", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Second Monitor Worth It for Working From Home?"},
    {"kw": "is an ergonomic chair worth the money", "cat": "home-office", "type": "comparison",
     "intent": "worthit",
     "title": "Is an Ergonomic Chair Worth the Money on a Budget?"},
    {"kw": "why is my webcam blurry", "cat": "home-office", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Webcam Blurry? 6 Fixes Before You Buy a New One"},
    {"kw": "why does my laptop overheat on a desk", "cat": "home-office", "type": "howto",
     "intent": "problem",
     "title": "Why Does My Laptop Overheat on a Desk? Cheap Fixes That Work"},
    {"kw": "why do my headphones hurt my ears after an hour", "cat": "home-office", "type": "howto",
     "intent": "problem",
     "title": "Why Your Headphones Hurt After an Hour (and How to Fix It)"},
    {"kw": "why is my wifi slow in one room", "cat": "home-office", "type": "howto",
     "intent": "problem",
     "title": "Why Is My Wi-Fi Slow in One Room? Cheap Fixes to Try First"},
    {"kw": "how much does a home office setup cost on a budget", "cat": "home-office", "type": "howto",
     "intent": "cost",
     "title": "How Much Does a Home Office Setup Cost on a Budget?"},
    {"kw": "how much does it cost to soundproof a home office", "cat": "home-office", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Soundproof a Home Office?"},
    {"kw": "best budget desk for a tiny bedroom", "cat": "home-office", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Desks for a Tiny Bedroom in {year}"},
    {"kw": "best cheap chair for long hours at a desk", "cat": "home-office", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Chairs for Long Hours at a Desk"},
    {"kw": "best budget lighting for video calls", "cat": "home-office", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Lighting for Video Calls in {year}"},
    {"kw": "best cheap laptop stand for neck pain", "cat": "home-office", "type": "comparison",
     "title": "Best Cheap Laptop Stands for Neck Pain"},
    {"kw": "best budget usb hub for a laptop", "cat": "home-office", "type": "comparison",
     "title": "Best Budget USB Hubs for a Laptop in {year}"},
    {"kw": "best cheap desk mat and cable tray", "cat": "home-office", "type": "comparison",
     "title": "Best Cheap Desk Mats and Cable Trays for a Clean Setup"},
    {"kw": "best budget microphone for meetings", "cat": "home-office", "type": "comparison",
     "title": "Best Budget Microphones for Meetings and Calls"},
    {"kw": "best cheap monitor for spreadsheets", "cat": "home-office", "type": "comparison",
     "title": "Best Cheap Monitors for Spreadsheet Work"},
    {"kw": "how to make a desk comfortable without buying a chair", "cat": "home-office", "type": "howto",
     "title": "How to Make Any Desk Comfortable Without Buying a Chair"},
    {"kw": "how to reduce eye strain from screens cheaply", "cat": "home-office", "type": "howto",
     "title": "How to Reduce Eye Strain From Screens (Cheap Fixes That Help)"},
    {"kw": "how to keep cables tidy on a rented desk", "cat": "home-office", "type": "howto",
     "title": "How to Keep Cables Tidy on a Desk You Can't Drill Into"},
    {"kw": "how to take better video calls without a ring light", "cat": "home-office", "type": "howto",
     "title": "How to Look Better on Video Calls Without Buying a Ring Light"},
    {"kw": "cheap home office upgrades that actually help", "cat": "home-office", "type": "list",
     "title": "10 Cheap Home Office Upgrades That Actually Help"},
    {"kw": "cheapest way to get a quiet home office", "cat": "home-office", "type": "list",
     "title": "The Cheapest Ways to Get a Quiet Home Office"},

    # ===================================================================
    # PETS  (pet)
    # ===================================================================
    {"kw": "crate vs playpen for a puppy", "cat": "pet", "type": "comparison",
     "intent": "vs",
     "title": "Crate vs Playpen for a Puppy: Which Should You Set Up First?"},
    {"kw": "clumping vs non clumping cat litter cost", "cat": "pet", "type": "comparison",
     "intent": "vs",
     "title": "Clumping vs Non-Clumping Cat Litter: Which Costs Less?"},
    {"kw": "automatic feeder vs scheduled feeding for dogs", "cat": "pet", "type": "comparison",
     "intent": "vs",
     "title": "Automatic Feeder vs Feeding by Hand: Is the Gadget Worth It?"},
    {"kw": "harness vs collar for a strong dog", "cat": "pet", "type": "comparison",
     "intent": "vs",
     "title": "Harness vs Collar for a Strong Dog: What's Safer?"},
    {"kw": "is pet insurance worth it for a young dog", "cat": "pet", "type": "comparison",
     "intent": "worthit",
     "title": "Is Pet Insurance Worth It for a Young Dog? Run the Numbers"},
    {"kw": "is a pet camera worth it for a cat", "cat": "pet", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Pet Camera Worth It for a Cat? (Or Just a Waste)"},
    {"kw": "is a water fountain worth it for cats", "cat": "pet", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Water Fountain Worth It for Cats Who Won't Drink?"},
    {"kw": "why does my cat ignore expensive toys", "cat": "pet", "type": "howto",
     "intent": "problem",
     "title": "Why Your Cat Ignores Expensive Toys (and What They Want Instead)"},
    {"kw": "why does my dog destroy every toy", "cat": "pet", "type": "howto",
     "intent": "problem",
     "title": "Why Your Dog Destroys Every Toy and What to Buy Instead"},
    {"kw": "why is my cat scratching the furniture", "cat": "pet", "type": "howto",
     "intent": "problem",
     "title": "Why Your Cat Scratches Furniture (and How to Redirect It)"},
    {"kw": "why does my litter box smell so fast", "cat": "pet", "type": "howto",
     "intent": "problem",
     "title": "Why Your Litter Box Smells So Fast and How to Fix It"},
    {"kw": "why does my dog refuse to walk in the rain", "cat": "pet", "type": "howto",
     "intent": "problem",
     "title": "Why Your Dog Refuses to Walk in the Rain (Simple Fixes)"},
    {"kw": "how much does a dog cost per month", "cat": "pet", "type": "howto",
     "intent": "cost",
     "title": "How Much Does a Dog Actually Cost Per Month?"},
    {"kw": "how much does it cost to keep a cat indoors", "cat": "pet", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Keep an Indoor Cat Per Year?"},
    {"kw": "how much does professional dog grooming cost", "cat": "pet", "type": "howto",
     "intent": "cost",
     "title": "How Much Does Dog Grooming Cost vs Doing It Yourself?"},
    {"kw": "best budget dog bed for a large dog", "cat": "pet", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Dog Beds for Large Dogs in {year}"},
    {"kw": "best cheap cat tree for small apartments", "cat": "pet", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Cat Trees for Small Apartments"},
    {"kw": "best cheap dog crate cover and mat set", "cat": "pet", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Dog Crate Covers and Mat Sets"},
    {"kw": "best cheap dog food for sensitive stomachs", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Dog Foods for Sensitive Stomachs"},
    {"kw": "best budget cat litter box with high sides", "cat": "pet", "type": "comparison",
     "title": "Best Budget Cat Litter Boxes With High Sides"},
    {"kw": "best cheap leash for a puller", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Leashes for Dogs That Pull"},
    {"kw": "best budget pet gate for wide openings", "cat": "pet", "type": "comparison",
     "title": "Best Budget Pet Gates for Wide Openings"},
    {"kw": "best cheap grooming brush for shedding dogs", "cat": "pet", "type": "comparison",
     "title": "Best Cheap Grooming Brushes for Heavy Shedders"},
    {"kw": "how to keep a dog busy while you work", "cat": "pet", "type": "howto",
     "title": "How to Keep a Dog Busy While You Work From Home"},
    {"kw": "how to stop a cat from waking you at 4am", "cat": "pet", "type": "howto",
     "title": "How to Stop Your Cat From Waking You at 4 AM"},
    {"kw": "how to save money on pet medication", "cat": "pet", "type": "howto",
     "title": "How to Save Money on Pet Medication Safely"},
    {"kw": "how to make cheap cat toys from things you own", "cat": "pet", "type": "howto",
     "title": "How to Make Cat Toys From Things You Already Own"},
    {"kw": "cheapest way to keep a dog cool in summer", "cat": "pet", "type": "list",
     "title": "The Cheapest Ways to Keep a Dog Cool in Summer"},
    {"kw": "cheap diy cat enrichment ideas that work", "cat": "pet", "type": "list",
     "title": "9 Cheap DIY Cat Enrichment Ideas That Actually Work"},

    # ===================================================================
    # GARDEN & OUTDOORS  (garden)
    # ===================================================================
    {"kw": "raised bed vs in ground garden for beginners", "cat": "garden", "type": "comparison",
     "intent": "vs",
     "title": "Raised Beds vs In-Ground Gardens for Beginners"},
    {"kw": "grow lights vs a sunny window for seedlings", "cat": "garden", "type": "comparison",
     "intent": "vs",
     "title": "Grow Lights vs a Sunny Window: What Seedlings Really Need"},
    {"kw": "hose reel vs hose cart for small yards", "cat": "garden", "type": "comparison",
     "intent": "vs",
     "title": "Hose Reel vs Hose Cart: What's Better for a Small Yard?"},
    {"kw": "plastic vs fabric grow bags for vegetables", "cat": "garden", "type": "comparison",
     "intent": "vs",
     "title": "Plastic Pots vs Fabric Grow Bags for Vegetables"},
    {"kw": "is a greenhouse worth it for a small garden", "cat": "garden", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Greenhouse Worth It for a Small Backyard Garden?"},
    {"kw": "is a soil test kit worth buying", "cat": "garden", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Soil Test Kit Worth Buying, or Can You Skip It?"},
    {"kw": "why are my tomato leaves turning yellow", "cat": "garden", "type": "howto",
     "intent": "problem",
     "title": "Why Your Tomato Leaves Turn Yellow (and What to Do)"},
    {"kw": "why is my garden hose leaking at the faucet", "cat": "garden", "type": "howto",
     "intent": "problem",
     "title": "Why Your Garden Hose Leaks at the Faucet (Cheap Fix)"},
    {"kw": "why do my potted plants dry out so fast", "cat": "garden", "type": "howto",
     "intent": "problem",
     "title": "Why Potted Plants Dry Out So Fast (and the Cheap Fix)"},
    {"kw": "why are my herbs dying indoors", "cat": "garden", "type": "howto",
     "intent": "problem",
     "title": "Why Your Indoor Herbs Keep Dying (Fixes That Work)"},
    {"kw": "why is my compost bin not heating up", "cat": "garden", "type": "howto",
     "intent": "problem",
     "title": "Why Your Compost Bin Isn't Heating Up and How to Fix It"},
    {"kw": "how much does it cost to start a vegetable garden", "cat": "garden", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Start a Vegetable Garden?"},
    {"kw": "how much does raised bed soil cost to fill", "cat": "garden", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Fill a Raised Bed With Soil?"},
    {"kw": "best budget grow light for herbs", "cat": "garden", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Grow Lights for Herbs in {year}"},
    {"kw": "best cheap raised bed kit for beginners", "cat": "garden", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Raised Bed Kits for Beginners"},
    {"kw": "best budget watering timer for vacations", "cat": "garden", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Watering Timers for When You're Away"},
    {"kw": "best cheap pruning tools for small gardens", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Pruning Tools for Small Gardens"},
    {"kw": "best budget compost bin for a small yard", "cat": "garden", "type": "comparison",
     "title": "Best Budget Compost Bins for a Small Yard"},
    {"kw": "best cheap seed starting trays", "cat": "garden", "type": "comparison",
     "title": "Best Cheap Seed Starting Trays and Kits"},
    {"kw": "best budget shade cloth for vegetable gardens", "cat": "garden", "type": "comparison",
     "title": "Best Budget Shade Cloth for Vegetable Gardens"},
    {"kw": "best affordable garden gloves that last", "cat": "garden", "type": "comparison",
     "title": "Best Affordable Garden Gloves That Actually Last"},
    {"kw": "how to grow vegetables in pots cheaply", "cat": "garden", "type": "howto",
     "title": "How to Grow Vegetables in Pots Cheaply"},
    {"kw": "how to keep weeds out of a garden bed cheaply", "cat": "garden", "type": "howto",
     "title": "How to Keep Weeds Out of a Garden Bed Without Chemicals"},
    {"kw": "how to save money on potting soil", "cat": "garden", "type": "howto",
     "title": "How to Save Money on Potting Soil (DIY Mix Recipe)"},
    {"kw": "how to start seeds indoors without a greenhouse", "cat": "garden", "type": "howto",
     "title": "How to Start Seeds Indoors Without a Greenhouse"},
    {"kw": "how to water plants cheaply while away", "cat": "garden", "type": "howto",
     "title": "How to Water Plants Cheaply While You're Away"},
    {"kw": "cheapest vegetables to grow for beginners", "cat": "garden", "type": "list",
     "title": "10 Cheapest Vegetables to Grow for Beginners"},
    {"kw": "cheap ways to protect plants from frost", "cat": "garden", "type": "list",
     "title": "9 Cheap Ways to Protect Plants From Frost"},

    # ===================================================================
    # ENERGY & SAVINGS  (energy)
    # ===================================================================
    {"kw": "led vs cfl bulbs cost over a year", "cat": "energy", "type": "comparison",
     "intent": "vs",
     "title": "LED vs CFL Bulbs: Real Cost Over One Year"},
    {"kw": "space heater vs central heating cost", "cat": "energy", "type": "comparison",
     "intent": "vs",
     "title": "Space Heater vs Central Heating: Which Costs Less to Run?"},
    {"kw": "tankless vs tank water heater savings", "cat": "energy", "type": "comparison",
     "intent": "vs",
     "title": "Tankless vs Tank Water Heater: Do You Really Save Money?"},
    {"kw": "smart thermostat vs manual thermostat savings", "cat": "energy", "type": "comparison",
     "intent": "vs",
     "title": "Smart Thermostat vs Manual: How Much Do You Save?"},
    {"kw": "is a smart power strip worth it", "cat": "energy", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Smart Power Strip Worth It, or Just Unplug Things?"},
    {"kw": "is a dehumidifier worth running all summer", "cat": "energy", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Dehumidifier Worth Running All Summer? Cost vs Comfort"},
    {"kw": "is solar worth it for a small home", "cat": "energy", "type": "comparison",
     "intent": "worthit",
     "title": "Is Solar Worth It for a Small Home on a Budget?"},
    {"kw": "why is my electric bill so high in winter", "cat": "energy", "type": "howto",
     "intent": "problem",
     "title": "Why Your Electric Bill Spikes in Winter (and What to Cut)"},
    {"kw": "why is my ac not cooling the house", "cat": "energy", "type": "howto",
     "intent": "problem",
     "title": "Why Your AC Isn't Cooling the House (Checks Before You Call)"},
    {"kw": "why is my fridge running all the time", "cat": "energy", "type": "howto",
     "intent": "problem",
     "title": "Why Your Fridge Runs Constantly (and What It Costs You)"},
    {"kw": "why does my water bill keep going up", "cat": "energy", "type": "howto",
     "intent": "problem",
     "title": "Why Your Water Bill Keeps Going Up (Leaks You Can Find)"},
    {"kw": "how much does it cost to run a space heater", "cat": "energy", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Run a Space Heater Per Hour?"},
    {"kw": "how much does it cost to run a dehumidifier", "cat": "energy", "type": "howto",
     "intent": "cost",
     "title": "How Much Does a Dehumidifier Cost to Run Per Month?"},
    {"kw": "how much does it cost to leave a fan on all day", "cat": "energy", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Leave a Fan On All Day?"},
    {"kw": "best budget smart thermostat for renters", "cat": "energy", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Smart Thermostats for Renters"},
    {"kw": "best cheap window insulation kit", "cat": "energy", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Window Insulation Kits for Cold Rooms"},
    {"kw": "best budget space heater for a small bedroom", "cat": "energy", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Space Heaters for a Small Bedroom"},
    {"kw": "best cheap led bulbs for a whole house", "cat": "energy", "type": "comparison",
     "title": "Best Cheap LED Bulbs for Replacing a Whole House"},
    {"kw": "best budget power strip with surge protection", "cat": "energy", "type": "comparison",
     "title": "Best Budget Power Strips With Surge Protection"},
    {"kw": "best cheap draft stopper for doors", "cat": "energy", "type": "comparison",
     "title": "Best Cheap Draft Stoppers for Doors and Windows"},
    {"kw": "how to find what uses the most electricity at home", "cat": "energy", "type": "howto",
     "title": "How to Find What Uses the Most Electricity in Your Home"},
    {"kw": "how to lower a water heating bill cheaply", "cat": "energy", "type": "howto",
     "title": "How to Lower Your Water Heating Bill Without Spending Money"},
    {"kw": "how to keep a house warm without raising the thermostat", "cat": "energy", "type": "howto",
     "title": "How to Keep a House Warm Without Touching the Thermostat"},
    {"kw": "cheapest ways to cut an electric bill this month", "cat": "energy", "type": "list",
     "title": "12 Cheapest Ways to Cut Your Electric Bill This Month"},

    # ===================================================================
    # TOOLS & DIY  (tools)
    # ===================================================================
    {"kw": "corded vs cordless drill for home use", "cat": "tools", "type": "comparison",
     "intent": "vs",
     "title": "Corded vs Cordless Drill for Home Use: Which to Buy First"},
    {"kw": "stud finder vs magnet for hanging shelves", "cat": "tools", "type": "comparison",
     "intent": "vs",
     "title": "Stud Finder vs Magnet: What's Better for Hanging Shelves?"},
    {"kw": "hand saw vs circular saw for beginners", "cat": "tools", "type": "comparison",
     "intent": "vs",
     "title": "Hand Saw vs Circular Saw for Beginners: Start With Which?"},
    {"kw": "wrench set vs adjustable wrench for homeowners", "cat": "tools", "type": "comparison",
     "intent": "vs",
     "title": "Wrench Set vs Adjustable Wrench: What a Homeowner Needs"},
    {"kw": "is an impact driver worth it for occasional diy", "cat": "tools", "type": "comparison",
     "intent": "worthit",
     "title": "Is an Impact Driver Worth It for Occasional DIY?"},
    {"kw": "is a multitool worth it for home repairs", "cat": "tools", "type": "comparison",
     "intent": "worthit",
     "title": "Is a Multitool Worth It for Home Repairs?"},
    {"kw": "why does my drill bit slip", "cat": "tools", "type": "howto",
     "intent": "problem",
     "title": "Why Your Drill Bit Slips (and How to Stop It)"},
    {"kw": "why does my hammer leave marks on wood", "cat": "tools", "type": "howto",
     "intent": "problem",
     "title": "Why Your Hammer Leaves Marks on Wood (Simple Fix)"},
    {"kw": "why does my drill battery die so fast", "cat": "tools", "type": "howto",
     "intent": "problem",
     "title": "Why Your Drill Battery Dies So Fast and How to Keep It Alive"},
    {"kw": "why is my screw stripping every time", "cat": "tools", "type": "howto",
     "intent": "problem",
     "title": "Why Screws Keep Stripping on You (and the One-Hand Trick)"},
    {"kw": "how much does it cost to build a basic tool kit", "cat": "tools", "type": "howto",
     "intent": "cost",
     "title": "How Much Does It Cost to Build a Basic Home Tool Kit?"},
    {"kw": "how much does a power drill cost for home use", "cat": "tools", "type": "howto",
     "intent": "cost",
     "title": "How Much Should You Spend on a Drill for Home Use?"},
    {"kw": "best budget drill for a first apartment", "cat": "tools", "type": "comparison",
     "intent": "scenario",
     "title": "Best Budget Drills for a First Apartment in {year}"},
    {"kw": "best cheap tool kit for renters", "cat": "tools", "type": "comparison",
     "intent": "scenario",
     "title": "Best Cheap Tool Kits for Renters (No Garage Needed)"},
    {"kw": "best budget socket set for car and home", "cat": "tools", "type": "comparison",
     "title": "Best Budget Socket Sets for Car and Home Repairs"},
    {"kw": "best cheap clamp set for woodworking", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Clamp Sets for Small Woodworking Projects"},
    {"kw": "best budget work gloves for diy", "cat": "tools", "type": "comparison",
     "title": "Best Budget Work Gloves for DIY Projects"},
    {"kw": "best affordable tape measure that lasts", "cat": "tools", "type": "comparison",
     "title": "Best Affordable Tape Measures That Last for Years"},
    {"kw": "best cheap level for hanging pictures", "cat": "tools", "type": "comparison",
     "title": "Best Cheap Levels for Hanging Pictures Straight"},
    {"kw": "how to hang a shelf without a stud finder", "cat": "tools", "type": "howto",
     "title": "How to Hang a Shelf Without a Stud Finder"},
    {"kw": "how to remove a stripped screw without tools", "cat": "tools", "type": "howto",
     "title": "How to Remove a Stripped Screw With Almost Nothing"},
    {"kw": "how to fix a loose cabinet hinge cheaply", "cat": "tools", "type": "howto",
     "title": "How to Fix a Loose Cabinet Hinge for Under $5"},
    {"kw": "how to patch a small hole in drywall cheaply", "cat": "tools", "type": "howto",
     "title": "How to Patch a Small Drywall Hole Cheaply"},
    {"kw": "cheapest tools every renter should own", "cat": "tools", "type": "list",
     "title": "10 Cheapest Tools Every Renter Should Own"},
    {"kw": "cheap diy fixes that save on repair bills", "cat": "tools", "type": "list",
     "title": "12 Cheap DIY Fixes That Save on Repair Bills"},
]
